"""Counterexample -> Verilator stimulus.

Turns a BMC trace into (a) a JSON trace artifact, (b) a synthesizable SV
testbench that replays the trace's inputs cycle by cycle against the
ORIGINAL RTL, and (c) drives Verilator (`--binary --assert`) to confirm the
assertion actually fires in simulation.  This closes the loop between the
formal model and the simulated design: a bug report from the prover is only
"confirmed" once Verilator reproduces it.

Replay fidelity: the prover constrains formally-uninitialized registers to
zero at frame 0 (engine option `zero_init_free_states`, on by default) which
matches Verilator's default two-state zero initialization, so traces replay
deterministically.
"""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .engine import Trace


@dataclass
class ReplayResult:
    confirmed: bool
    tb_file: Path
    trace_file: Path
    sim_log: str
    fail_cycle: int | None = None


def _sanitize(name: str) -> str:
    return name.lstrip("\\")


def trace_to_json(trace: Trace, out_file: Path, top: str, source: str) -> None:
    out_file.write_text(json.dumps({
        "format": "sparkle-fv-trace-v1",
        "top": top,
        "source": source,
        "violated_assertion": trace.bad_name,
        "depth": trace.depth,
        "inputs_per_cycle": trace.inputs,
        "initial_state": trace.states0,
    }, indent=2))


def _port_decls(inputs: list[str], widths: dict[str, int], clocks: set[str]) -> str:
    decls = []
    for name in inputs:
        w = widths.get(name, 1)
        rng = f"[{w - 1}:0] " if w > 1 else ""
        decls.append(f"  logic {rng}{_sanitize(name)};")
    return "\n".join(decls)


def generate_testbench(trace: Trace, top: str, out_file: Path,
                       clock_names: tuple[str, ...] = ("clk", "clock", "clk_i")
                       ) -> Path:
    """Emit an SV testbench replaying the trace inputs against `top`.

    One BMC frame corresponds to one clock cycle.  Non-clock inputs are
    driven to the frame's values just after the previous rising edge (i.e.
    in the low phase), so they are stable at the next posedge — matching
    the BTOR2 semantics where frame k's inputs feed the k->k+1 transition.
    """
    names = sorted(trace.inputs[0].keys()) if trace.inputs else []
    clocks = {n for n in names if _sanitize(n) in clock_names}
    data_inputs = [n for n in names if n not in clocks]
    widths = trace.input_widths

    conns = ",\n".join(f"    .{_sanitize(n)}({_sanitize(n)})" for n in names)
    stim_lines = []
    for f, frame in enumerate(trace.inputs):
        assigns = []
        for n in data_inputs:
            w = widths.get(n, 1)
            assigns.append(f"{_sanitize(n)} = {w}'d{frame.get(n, 0)};")
        stim_lines.append(f"      // cycle {f}\n      " + " ".join(assigns)
                          if assigns else f"      // cycle {f} (no data inputs)")
        stim_lines.append("      @(posedge clk); #1;")
    stim = "\n".join(stim_lines)
    clk_decl = "" if any(_sanitize(c) == "clk" for c in clocks) else \
        "  logic clk;\n"

    tb = f"""// Auto-generated by sparkle-fv: replays a formal counterexample
// for assertion '{trace.bad_name}' (violated at cycle {trace.depth}).
`timescale 1ns/1ps
module tb_sparkle_fv;
{_port_decls(names, widths, clocks)}
{clk_decl}
  {top} dut (
{conns}
  );

  initial clk = 0;
  always #5 clk = ~clk;
{"".join(f"  assign {_sanitize(c)} = clk;" + chr(10) for c in clocks if _sanitize(c) != "clk")}
  initial begin
    $display("[sparkle-fv] replaying %0d-cycle counterexample", {trace.depth + 1});
    #1;
{stim}
    $display("[sparkle-fv] replay finished without assertion failure");
    $finish;
  end

  initial begin
    #{10 * (trace.depth + 3) + 100};
    $display("[sparkle-fv] watchdog timeout");
    $finish;
  end
endmodule
"""
    out_file.write_text(tb)
    return out_file


def run_verilator(tb_file: Path, design_file: Path, top: str, work_dir: Path,
                  timeout_s: float = 300.0) -> tuple[bool, str, int | None]:
    """Build and run the replay under Verilator with --assert.

    Returns (assertion_fired, log, fail_cycle_estimate).
    """
    work_dir.mkdir(parents=True, exist_ok=True)
    build = subprocess.run(
        ["verilator", "--binary", "--assert", "-Wno-fatal", "--timing",
         "-o", "sim_replay", "--Mdir", str(work_dir / "obj_dir"),
         "--top-module", "tb_sparkle_fv",
         str(design_file), str(tb_file)],
        capture_output=True, text=True, timeout=timeout_s)
    if build.returncode != 0:
        return False, "VERILATOR BUILD FAILED\n" + build.stderr[-3000:], None
    sim = subprocess.run([str(work_dir / "obj_dir" / "sim_replay")],
                         capture_output=True, text=True, timeout=timeout_s)
    log = sim.stdout + sim.stderr
    fired = ("Assertion failed" in log) or ("%Error" in log and "assert" in log.lower())
    cycle = None
    m = re.search(r"time (\d+)", log)
    if m:
        cycle = int(m.group(1)) // 10
    return fired, log[-4000:], cycle


def replay(trace: Trace, top: str, design_file: Path, out_dir: Path,
           source_label: str = "") -> ReplayResult:
    """Full loop: trace artifacts + testbench + Verilator confirmation."""
    out_dir.mkdir(parents=True, exist_ok=True)
    trace_file = out_dir / "trace.json"
    trace_to_json(trace, trace_file, top, source_label)
    tb_file = generate_testbench(trace, top, out_dir / "tb_replay.sv")
    fired, log, cycle = run_verilator(tb_file, design_file, top, out_dir)
    (out_dir / "replay.log").write_text(log)
    return ReplayResult(confirmed=fired, tb_file=tb_file, trace_file=trace_file,
                        sim_log=log, fail_cycle=cycle)
